# Generated by Django 6.0.2 on 2026-02-07 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch', models.CharField(max_length=20)),
                ('pick_rate', models.FloatField()),
                ('win_rate', models.FloatField()),
                ('ban_rate', models.FloatField()),
                ('games_played', models.FloatField()),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='champions.champion')),
            ],
            options={
                'unique_together': {('champion', 'patch')},
            },
        ),
    ]
