# Generated by Django 6.0.2 on 2026-02-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championstats',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
