# Generated by Django 6.0.2 on 2026-02-08 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("champions", "0002_rename_updatedat_championstats_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="championstats",
            name="ban_rate",
        ),
        migrations.RemoveField(
            model_name="championstats",
            name="games_played",
        ),
        migrations.RemoveField(
            model_name="championstats",
            name="pick_rate",
        ),
        migrations.RemoveField(
            model_name="championstats",
            name="win_rate",
        ),
        migrations.AddField(
            model_name="champion",
            name="blurb",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="champion",
            name="partype",
            field=models.CharField(
                choices=[
                    ("Mana", "Mana"),
                    ("Energy", "Energy"),
                    ("None", "None"),
                    ("Rage", "Rage"),
                    ("Shield", "Shield"),
                    ("BloodWell", "Blood Well"),
                    ("Fury", "Fury"),
                    ("ManaShield", "Mana Shield"),
                ],
                default="Mana",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="champion",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="champion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="armor",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="armorperlevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="attackdamage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="attackdamageperlevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="attackrange",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="attackspeed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="attackspeedperlevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="crit",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="critperlevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="hp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="hpperlevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="hpregen",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="hpregenperlevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="movespeed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="mp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="mpperlevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="mpregen",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="mpregenperlevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="spellblock",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="championstats",
            name="spellblockperlevel",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="champion",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="championstats",
            name="patch",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name="ChampionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full", models.CharField(blank=True, max_length=50)),
                ("sprite", models.CharField(blank=True, max_length=50)),
                ("group", models.CharField(blank=True, max_length=50)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "champion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="champions.champion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChampionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attack", models.IntegerField()),
                ("patch", models.CharField(blank=True, max_length=10)),
                ("defense", models.IntegerField()),
                ("magic", models.IntegerField()),
                ("difficulty", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "champion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="info",
                        to="champions.champion",
                    ),
                ),
            ],
            options={
                "unique_together": {("champion", "patch")},
            },
        ),
    ]
